export const SECTIONS = [
  {
    title: "(1) MANAGEMENT COMMITMENT:",
    items: [
      "Is there a safety policy?",
      "Is the safety policy displayed at site?",
      "Is everyone aware of the contents of the safety policy?",
      "Are there Project specific HSE service delivery guidelines and safety procedures?",
      "Are the employees aware of the Project specific HSE service delivery guidelines?",
      "Is there a safety organisation?",
      "Are competent safety professional available at site?",
      "Is there a safety committee?",
      "Are the recommendations of the committee implemented?",
      "Is project management actively participating in E&HS Programs?",
    ],
  },
  {
    title: "(2) GATE MANAGEMENT",
    items: [
      "Are the details of the project displayed at the entrance of the project ?",
      "Are Emergency contact numbers displayed at the entrance and inside the project site?",
      "Are the site safety rules displayed  at the entrance  & inside the project site ?",
      "Is a saperate access given to pedestrains and vehicle movements from the entrance of the project site ?",
      "Is the routing signages for vehicles displayed at the entrance gate ?",
      "Is there a security check for all vehicle movements at the time or entry & exit ?",
      "Wether the ID cards with photographs isssued to all workers?",
      "Is there an effective communication system at the gate management ?",
      "Whether no child labor/ senior citizens enganged  for any activity in the project site ?",
      "Is the safety helmets colour code displayed at check post of the project site  ?",
    ],
  },
  {
    title: "(3) Labor welfare",
    items: [
      "Are the entry roads / walkways / passages to camp kept clear?",
      "Are the walkways & roads are even and free from water logging?",
      "Is the entry inside workmen camp restricted?",
      "Is there any emergency communication system established?",
      "Is the Workmen camp constructed with Non-Fire Hazard Material?",
      "Whether disinfection activities carried out on weekly basis?",
      "Is shelter strong enough to with stand wind pressure?",
      "Are Fire Extinguishers & Fire Buckets available and maintained regularly?",
      "Is the garbage of kitchen being disposed off every day?",
      "Are gas cylinders & other flammable materials kept in safe area (away from fire)?",
      "Are all the emilities being given to the workers at labor coloney & site?",
      "a) Drinking water",
      "b)Toilets",
      "c)power",
      "d)Sanitation",
      "f)common area lightings",
      "g)creches",
      "h)canteen",
      "Are the medical checkups carried out at labor camp regularly?",
      "Is the test certificate available for drinking water provided at labor camp ?",
    ],
  },
  {
    title: "(4) SAFETY TRAINING & AWARENESS PROGRAMS:",
    items: [
      "Are employees given safety orientation training?",
      "Are employees given  specialized training where needed?",
      "Are tool box talks regularly conducted?",
      "Are safety bulletin boards at site?",
      "Are safety material displayed at site?",
      "Are there site safety instructions to various trades?",
      "Are method statements made for critical activities?",
      "Are safety procedures  made for routine and new activities?",
      "Are workers participating in formulating safety procedures?",
      "Are employees aware of the safety procedures?",
    ],
  },
  {
    title: "(5) EMERGENCY RESPONSE:",
    items: [
      "Is there a first aid centre at site?",
      "Is the First Aid Centre equipped with the required medicines and accessories?",
      "Is there a qualified First-aider  to handle First-aid centre?",
      "Is there any arrangement with hospital for emergency treatment?",
      "Is there an emergency response team?",
      "Is the team trained on emergency response procedures?",
      "Are workers aware of the emergency procedures?",
      "Are employees aware of the actions to be taken in case of :",
      "Accidents",
      "Fire",
      "Gas Leakeage",
      "Electric shock",
      "Gas Cylinders on fire",
      "Sun Stroke",
      "Snake/ Scorpion bites",
      "Are emergency telephone numbers displayed?",
      "Is emergency vehicle/ ambulance available at site?",
      "Are trained first aiders available at site?",
      "Are there assembly points available which is easily approachble?",
      "Is there an effective communication system?",
      "Are mock drills conducted at regular intervals?",
      "Is there a emegency evacuation plan available at site as per the present site conditions (revised periodically as per site progress?",
      "IS the emergency evacuation paln displayed at all working locations & explained to all the workers in site ?",
      "Is the routing signages available to guide the workers to reach emergency exits & assembly points ?",
      "Proper illumination provided in emergency exit ?",
      "Is the emergency exits free from obstructions ?",
    ],
  },
  {
    title: "(6) PERSONEL PROTECTIVE EQUIPMENT:",
    items: [
      "Are all persons wearing safety helmets while on site?",
      "Are the workers using the chin strap of their safety helmets?",
      "Is everyone wearing safety shoes while on site?",
      "Is everyone wearing safety goggles where needed?",
      "Are the workers wearing suitable hand gloves while handling rough objects?",
      "Are workers wearing full body safety harness while working at heights?",
      "Are the workers anchoring their safety harnesses?",
      "Are workers wearing respirators when exposed to dust, harmful , chemicals and poisonous gases etc..?",
      "Are workers using suitable PPE as per the hazards?",
      "Are there sufficient stock of PPE?",
      "Are the PPE regulary inspected for there good condition?",
      "Are PPE properly handled and stored?",
    ],
  },
  {
    title: "(7) Blasting",
    items: [
      "Does the permit for blasting operation implemented ?",
      "Explosives stored, transported and used as per statutory requirements ?",
      "Procedure for drilling, blasting & handling misfire meets statutory requirements ?",
      "System of evacuation of people, warning & preventing re-entry is adequate ?",
      "Is the explosive stock registers & forms maintained as per statutory requirments ?",
    ],
  },
  {
    title: "(8) Excavation",
    items: [
      "Whether appropriate slope / shoring system provided ?",
      "Whether proper access & egress provided ?",
      "Work permit system implemented where needed ?",
      "Whether soil dumped sufficiently away from pit ?",
      "Whether the Barricade & lighting arrangement satisfactory for the Trench/Excavation/Chamber ?",
      "Are the relavent safety signages displayed at working areas (Trench/Excavation/Chamber) ?",
    ],
  },
  {
    title: "(9) Piling",
    items: [
      "Are the lifting tools and tackles (Cranes/winch/slings/D-shackles) inspected by Competent Person?",
      "Is tagline used while handling piles/casings?",
      "Are the moving and rotating parts of the piling system guarded?",
    ],
  },
  {
    title: "(10) DEMOLITION",
    items: [
      "Is the surrounding area surveyed and recorded before starting the activity ?",
      "Is there a approved demolishan plan ?",
      "Are the electrical cable connection/ water/ steam /gas line etc Disconnection and recorded  ?",
      "Is there a plan for removal debris to a safe place ?",
      "Is the method statement, Job safety analysis and risk assessment made before starting the work ?",
      "Emergency preparedness available like fire extinguisher ,first aid, ambulance etc ?",
      "Is the tool box talks carried out to the team & recorded ?",
      "Is any specialised training giving as per the project status ?",
    ],
  },
  {
    title: "(11) WORK AT HEIGHTS:",
    items: [
      "LADDERS:",
      "Are the ladders checked and inspected before use and at regular intervels?",
      "Are the defective ladders removed from site?",
      "Are the ladders placed as per safety requirements i.e. At an angle of 75 degrees with the horizontal?",
      "Are the ladders secured properly?",
      "Is the ladder extending 1m above the landing step?",
      "Are the ladders properly stored?",
      "Are persons ascending and descending the ladder in a safe manner?",
      "Are the ladders obstructing the passages?",
      "Are the ladders likely to be hit by movement of persons/vehicles?",
      "Is the identification marks given to all the ladders at site ?",
      "Is the ladder inspection register regularly maintained ?",
    ],
  },
  {
    title: "(12) SCAFFOLDS & WORKING PLATFORMS:",
    items: [
      "Is Approved Erection Scheme followed?",
      "Are the scaffolds designed as per the load requirement?",
      "Are scaffolds erected under the supervision of a trained person?",
      "Are the scaffolding material suitable for the purpose?",
      "Are the scaffolds erected on level ground with proper sole boards and base plates?",
      "Are the scaffolds plumb with adequate cross bracings?",
      "Are sufficient tie pins provided for the tower  scaffolds?",
      "Are platform boards inspected and are in good condition?",
      "Are the platforms fully boarded without openings?",
      "Are hand rails, mid rails and toe boards fixed for the platforms?",
      "Is there a proper access to reach the platforms?",
      "Are workers protected from falling objects?",
      "Is the base to height ratio maintained at 1:4?",
      "Are they inspected and tagged by competent person?",
      "Is the scaffold permit taken before using?",
      "Are green/red tags attached as per the conditions of the scaffolds?",
    ],
  },
  {
    title: "(13) Mobile scaffolding",
    items: [
      "Do mobile scaffolds have lockable castor wheels ?",
      "Are the wheels locked when in use ?",
      "Is safe internal ladder access available ?",
      "Is the ht >3 times the least width of the base ?",
      "Do out riggers need to be used ?",
      "Are the mobile scaffolds stable?",
      "Is the derrick erected properly and adequate no of guys are provided at 45o slope?",
      "Usage of tool bags, and securing hand tools against fall in place?",
      "Whether adequate manpower deployed for the tower erection activity?",
      "Is there a height watch man available for height works ?",
    ],
  },
  {
    title: "(14) Fall Prevention & Protection",
    items: [
      "Is there a site specific fall protection plan in place?",
      "Are workers trained in the fall protection procedures?",
      "Are open edges and floor cutouts properly barricaded?",
      "Are staircases provided with temporary railings?",
      "Are caution boards fixed at danger points?",
      "Are workers using full body harness?",
      "Have the workers anchored safety harness to a strong anchoring point?",
      "Are lifelines provided where anchoring points are available?",
      "Are fall arresters provided while climbing rope ladders?",
      "Are safety nets fixed where needed?",
      "Are sfety nets securely fixed?",
      "Are debris on the safety nets regulary cleaned?",
      "Are safety nets subjected to fire hazards?",
    ],
  },
  {
    title: "(15) ELECTRICAL:",
    items: [
      "Is electrical installation made as per the load requirement?",
      "Are the installation made of Industrial type fittings?",
      "Is adequate lightings provided for work areas and passages?",
      "Is  illumination study made around the site?",
      "Is the instalation suitable for weather conditions?",
      "Is the instalation certified by Licenced Supervisor?",
      "Are ELCB's/MCB's provided in the circuit?",
      "Are the distrubution boards protected from rain and water?",
      "Are the cables protected from mechanical damages?",
      "Are cables located at over head positions with sufficient head clearence?",
      "No joints on cables lying on ground?",
      "No cables lying on ground causing trip hazard?",
      "Are electrical equipment provided with proper earthing?",
      "Are ELCB'sand MCB's tested periodically?",
      "No single insulated electrical wires instead of double insulated PVC cables?",
      "Are the insulations regularly inspected and records maintained?",
      "Are Lock out/ Tag out procedures followed?",
      "Are the access to electrical panels free from obstructions?",
      "Are required Fire extingushers provided near the electrical panels?",
      "Is there any artificial rescusation charts displayed near electrical panels?",
      "Is there a full time licensed electrician in the site ?",
      "Are the rubber mats provided in front of all PDBs, DBs ?",
      "Are the Pannel boards & DBs have ID numbers ?",
      "Is the DBs are with contunity earthing?",
      "Is the electrical safety awareness posters, signages displayed inside the site and working areas ?",
    ],
  },
  {
    title: "(16) Stringing",
    items: [
      "Is stringing scheme incorporated with HSE requirement ?",
      "Whether adequate discharge rods are available & being used. ?",
      "Adequate line patrolling, signal men & safety stewards are deployed?",
      "Whether work method adopted for movement of men over conductors (for come along clamp removal, placing spacers etc) safe. ?",
      "Whether all road, rail & power line along the right of way identified and documented ?",
    ],
  },
  {
    title: "(17) Material Handling:",
    items: [
      "Is safe method of lifting manually being followed by the workmen?",
      "Are proper liftying accessories provided for manual handling ?",
      "Are personnel using body mechanics when lifting and carrying?",
      "Are the workers not lifting excess loads?",
      "Are the workmen using personal protective equipments while handling materials?",
      "Are workmen trained in material handling?",
      "Are workmen moving near moving machinery, pinch points etc.. where they may get injured?",
    ],
  },
  {
    title: "(18) Material Storage:",
    items: [
      "Are materials stored in an orderly manner?",
      "Are chemicals stored along with other materials in the stores?",
      "Is there proper arrangement for used and not used materials at stores?",
      "Is the MSDS displayed near the hazardious materials ?",
      "Are the stacks protected from collapse?",
      "Are the material protected from weather and rain?",
      "Are adequate precautions taken against fire hazard?",
      "Are the projected ends properly protected?",
      "Are the contents of the containers properly identified and labelled?",
      "Is there adequate ventilation?",
      "Is there a separate store  for cumbustable and chemicals with adequate precautions ?",
      "Are fire precautions taken where flammable materials  are stored?",
      "Is there a Emergency EXIT provided for the stores ?",
    ],
  },
  {
    title: "(19) Fire Prevention & Control:",
    items: [
      "Is waste accumulating in hoist shafts, corners etc…?",
      "Are waste bins provided at appropriate locations?",
      "Are any electrical circuits not overloaded?",
      "Are flammable materials stored separately?",
      "Are fire extinguishers available at site?",
      "Are the fire extinguishers suitable for the nature of fire?",
      "Are the fire extinguishers placed near the source of fire and are easilly accessible?",
      "Is  flame cutting and welding taking place with proper fire precautions?",
      "Are fire watchmen provided for hot works?",
      "Are there trainned persons to fight fire?",
      "Is there enough water and fire hoses at sitefor fightting fire?",
    ],
  },
  {
    title: "(20) Plant & Mobile Equipment:",
    items: [
      "Are the moving parts guarded?",
      "Are these operators trained?",
      "Are Machine opertors  medical examination carried out?",
      "Are theses Machine opertors fitness certicates available?",
      "Are the machines maintained in good condition?",
      "Are the workers protected from noise and fumes?",
      "Is noise study made?",
      "Is there adequate space around the machinery for maintenance works?",
      "Is the safety inspection check list maintained regularly before starting the works ?",
    ],
  },
  {
    title: "(21) GRINDING MACHINES:",
    items: [
      "Are the grinding wheels adequately guarded?",
      "Are  the operators trained for fixing the wheel?",
      "Are precautions taken against flying fragments of disintegrated wheel?",
      "Are the wheels fitted as per the designed speed and correctly fitted on the spring wheel?",
      "Is the rpm clearly marked on the machine?",
      "Is the surrounding area kept neat and tidy and free of obstructions?",
      "Are the operators using PPE to protect against flying particles?",
      "Is the gap between the wheel and the job rest properly adjusted and maintained?",
    ],
  },
  {
    title: "(22) Hand Tools & Power Tools",
    items: [
      "Are the hand tools in good working condition?",
      "Are they stored in a proper manner?",
      "Are damaged tools removed from use?",
      "Are appropriate tools available for the job?",
      "Are tools being used only for their proper intended use?",
      "Are grinding machines provided with guards over the wheels?",
      "Are the grinding wheels inspected for the expiry date?",
      "Is ring test done for abrasive wheels before fixing?",
      "Are the wheels suitable for the speed of the machine?",
      "Are the power tools provided with earth connection?",
      "Are the power tools handled properly?",
      "Are the handles of the tools free from splits and cracks?",
      "No mushroomed heads over the hammers, chisels and other impact tools?",
      "No edges for tooth of cutting tools kept sharp?",
    ],
  },
  {
    title: "(23) PNEUMATIC TOOLS",
    items: [
      "Is there misuse of compressed air?",
      "Is horseplay with compressed air forbidden?",
      "Are persons dusting their clothes with compressed air?",
      "Are the joints in the air lines made with purpose made connections?",
      "Are the pneumatic tools checked for faulty governors which may result in overspeeding?",
      "Is air supply to the tool disconnected when the tool is left unattended?",
    ],
  },
  {
    title: "(24) Hoisting Equipments",
    items: [
      "Are workers trained in proper rigging, flagging and hoisting procedures?",
      "Are loads correctly rigged?",
      "Are lifting equipment tested and certified?",
      "Are slings properly loaded as per the load chart?",
      "Are safety catches provided on the hooks of the lifting equipments?",
      "Are tag lines used while lifting materials?",
      "Is the area barricaded where the load is being lifted?",
      "Are lifting  plans made for the erection of heavy equipment/ Structures?",
      "Are persons working under suspended loads?",
      "Are all the lifiting accessories are with ID & certified by competent authority ?",
      "Are loads correctly rigged?",
      "All concrete buckets tested and SWL mentioned with ID marks ?",
    ],
  },
  {
    title: "(25) MOBILE CRANES",
    items: [
      "Is the crane  inspected by the Operator & recorded prior to use.",
      "Is the carne inspected weekly by a P&M In-Charge, and  record is kept. ?",
      "Is the crane load test carried out by a Competent Person before putting it in to work & regularly in every six months",
      "Whether preventive Maintenance is carried out on every crane and check list is maintained ?",
      "Is the crane operator  is trained and competent ?",
      "crane rated loaded capacities for varying radius of the Boom, operating speeds and instructions are displayed and are visible to the operator ?",
      "Crane operators and signalmen  men are trained in the use hand signals and illustrations are displayed on site ?",
    ],
  },
  {
    title: "(26) TOWER CRANES ( to verify from  P&M records )",
    items: [
      "Whether the stability of foundation is as per approved drawing ?",
    ],
  },
  {
    title: "(26 A) Mast Section : \nIs  the Mast & Fasteners are as per the manufacturers manual ?",
    items: [
      "Is the climbing ladder mountings and platforms are in good conditions ?",
      "Are the tie-collar mounting and Pins are as per the specifications ?",
      "Is the load Chart Displayed on crane mast ?",
      "Is the lightening arrestor available  ?",
    ],
  },
  {
    title: "(26 B) Swing Unit :",
    items: [
      "Is the Cat Head, the revolving bolts, Cabin Mounting Pins & Collar pins are checked and recorded ?",
      "Is the Swing Brake, Limit switch & Alarm regularly maintained & recorded ?",
      "Is the Operators Visibility & Wind screen is satisfactory ?",
      "Is the Anemometer functioning properly ?",
      "Is the aviation lamp is functional (Reqd. for 30mt and above) test report available ?",
      "Is Fire Extinguisher installed at operators cabin & ground level ?",
      "Whether regular checks conducted and recorded for Emergency Stop button ?",
    ],
  },
  {
    title: "(26 C) Counter Jib",
    items: [
      "Is the Counter Jib Mounting Pins and Cotter Pins checked and recorded ?",
      "Is the Platform mounting pins, handrail etc checked & recorded ?",
      "Is the mounting of the hoist winches checked and recorded ?",
      "Is the  Pins and cotter pins of the Tie Rods checked and recorded ?",
      "Is the Structural stability of platform & counter weights checked and recorded ?",
    ],
  },
  {
    title: "(26 D) Main Jib",
    items: [
      "Is the Mounting Pins and Cotter Pins checked and recorded  ?",
      "Is the Tie rod pins and cotter pins checked and recorded",
      "Is  Jib Inserts connecting pins and cotter pins checked and recorded ?",
      "Is the light fitting mounting for tightness inspected and recorded ?",
      "Is the SWL displayed on main jib for various operating radius & recorded ?",
    ],
  },
  {
    title: "(26 E) Hoist",
    items: [
      "Is the condition of wire rope checked and recorded ?",
      "Whether over hoist limit switch is in good working condition ?",
      "Is the break pads for excessive wear inspected and recorded",
      "Is the rope swiel for free rotation or not ?",
      "Is the Moment Cut off Limit Switch checked and recorded ?",
      "Is the break Cylinder for proper function and leakage is in satisfactory condition ?",
    ],
  },
  {
    title: "(26 F) Trolley",
    items: [
      "Is the Trolley rope, break and lock arrangement are inspected & recorded ?",
      "Is the working platform, extreme end limit switches inspected & recorded ?",
    ],
  },
  {
    title: "(27) Elevators & Service Shafts",
    items: [
      "Is the scaffolding properly erected?",
      "Is the working platforms placed & tied properly?",
      "Is sufficient ventilation & illumination provided?",
      "Are the ropes & chain pulleys are in good condition?",
      "Secondary fall protection and head protection provided?",
      "Proper signages & caution boards displayed at working area ?",
      "Toolbox meeting conducted before starting the activity ?",
      "Is the scuffolds ,working platforms checked and recorded before starting the works",
      "Is the work permit issued after throughly inspecting the area  ?",
      "Is all the electrical connections & cables proper checked ?",
    ],
  },
  {
    title: "(28) Environment",
    items: [
      "Are the waste materials segregated and disposed off in designated place or re-used ?",
      "Is the waste water discharged without harming surrounding environment?",
      "Spill control & Proper Collection of Oil ?",
      "Dust control measures adequate ?",
      "Noise control measures adequate ?",
      "Is local scrap yard provided?",
    ],
  },
  {
    title: "(29) House Keeping:",
    items: [
      "Is the site kept neat and tidy?",
      "Is there a waste management plan?",
      "Is there a proper arrangement for regular collection and disposal of waste materials?",
      "Are walkways clearly defined and unobstructed?",
      "Are materials and equipments stored properly?",
      "Is local scrap yard provided?",
      "Are there no projecting nails on the timbers?",
      "Are sanitory conditions of toilets good,cleaned and maintained regularly ?",
      "Is there adequate water supply for sanitation?",
      "Is there an easy access to Electrical control panels, Fire extinguisheres, First Aid boxes etc…?",
    ],
  },
  {
    title: "(30) DIESEL GENERATOR (DG)",
    items: [
      "Whether the continuity and tightness of earth conductor are checked?",
      "Mention the SWG of the earth conductor used ?",
      "Whether earth resistance is measured?",
      "Mention the value of Earth Resistance ?",
      "Is DG provided under shed / cover?",
      "Whether entry is restricted into the DG room?",
      "Are cable trenches are covered?",
      "Is insulation provided on the battery terminals?",
      "Is thermal insulation done for the DG exhaust ?",
      "Whether stack height is maintained as per Environment requirements given in procedure manual?",
      "Whether DG exhaust is diverted out side the shed?",
      "Are all the rotating parts of DG guarded (coupling, radiator fan)?",
      "Whether any leakage of fuel / oil in the DG room?",
      "Whether DG surrounding is free from flammable material?",
      "Whether fire extinguisher / fire buckets with stand are provided?",
      "Whether fire extinguisher / fire buckets with stands are provided?",
      "Whether DG is fitted with Acoustics & Silencer insulations?",
    ],
  },
  {
    title: "(31) CONFINED SPACE",
    items: [
      "Is there a list of persons authorised to enter confined space ?",
      "is the team been trained in dealing with the specified hazards ?",
      "Is the medical fitness certificates obtained for every six months ?",
      "Is the oxygen levels tested and recorded  (19.5% - 23.5%) ?",
      "Is the working area is of Explosibility of (0%) and recorded ?",
      "Is the Corbon monoxide level tested and recorded (50 PPM Max )",
      "Is the Corbon Dioxide level tested and recorded (1200 ppm Max)",
      "Is the temperature recorded before starting the activity in the confined space ?",
      "Is the air flow tested and recoreded in the confined space ?",
      "Are all the rescue devices & measures are in place and recorded before starting the activity ?",
      "Is sufficient illumination provided inside the confined area ?",
      "Is the work permit issued after throughly inspecting the area  ?",
    ],
  },
  {
    title: "(32) GAS WELDING AND CUTTING (HOT WORKS )",
    items: [
      "Is the tool box talks conducted before starting the activity ?",
      "Are the welders qualified for carry out the activity ?",
      "Is the work permit issued after inspecting the equipments ?",
      "Is the cylinder storage as per the statutory requirements ?",
      "Is the location of cylinder bank is safe ?",
      "Is there a fire watchmen while carrying out the job ?",
      "Is the area immediately below the work spot, been cleared / removed of oil, grease, waste cotton & other cumbustable materials ?",
      "Has Gas concentration been tested in case there is gas valve/gas line nearby?",
      "Is the trolleys suffcient in numbers and being used while doing hot works ?",
      "Have fire extinguishers been kept handy at site?",
      "Has tin sheet/ wet gunny bag/ fire retardant cloth / sheet been placed to prevent sparks from causing fire?",
      "Has water hose connection been made for continuous water spray?",
      "Have all the drain inlets (if any) been closed?",
      "Is the flash back arresters available both at torch & cylinders  ?",
      "Is the non returnvalve is in place ?",
    ],
  },
  {
    title: "(33) WELDING MACHINES",
    items: [
      "Is the Welding Machine  having calibration certificate ?",
      "Is the Welding Cables are without joints ?",
      "Are the Lugs of Welding  machine proper & inspected?",
      "whether the torch of the Welding cable  inspected ?",
      "Body earthing given on the welding machine ?",
      "Is  the Welding Machine placed dry surface ?",
      "Fire Extinguisher or fire point provided nearby ?",
      "Are the Welding location covered with Fire Blanket/ Tin sheet etc?",
      "whether the Welding machine serial no,  inspection date and due  stickered/ pasted on the machine ?",
    ],
  },
  {
    title: "(34) PAINTING",
    items: [
      "Are the painters using required PPEs like chemical cartridge type mask, handgloves etc..?",
      "Are there sufficient ventilations in the painting area?",
      "Are the fumes and gases not affecting the other workers in the surrownding area?",
      "Are the painting areas properly barricaded and marked?",
      "Are the materials like thinners and paints stored in a safe area?",
      "Is the area clear from sparking producing equipments?",
    ],
  },
  {
    title: "(35) Other safety related issues",
    items: [
      "Are the work permits procedures in place ?",
      "Are the check list being implemented as per the approved HSE project specific service deliver guidelines?",
      "Hazard identification and risk analysis for entire project site ?",
      "Is adequate illumination provided for  project site, working areas and passages?",
      "Is the mansoon action plan prepared for the project site ?",
      "Whether all the safety documents are regularly maintained ?",
      "Is there  fire point check lists maintained ?",
      "Is the earth pit resistance regularly checked and recorded ?",
      "Whether incidents investigation  carried out with a  case studies, lessons learnt disseminated effectively?",
      "First aid cases analyzed, critical areas identified, corrective action taken ?",
      "Is there any disciplinary  procedure for sub contractors for voilation of safety at site ?",
      "whether safety officer fully aware of the waste management plan to be implemented for  a green building concept ?",
      "Is the health register maintained at site to analyse occupational illhealth of the workers  ?",
      "Whether all the safety documents are as per ISO requirement ?",
      "Is the safety officer aware of the list of machinary equipment tools, going  to be used in the site.",
      "Is the line management effective in implementing safety at site ?",
      "Details of Safety promotional activities conducted by Management at project sites ?",
    ],
  },
];